### ISSUE TITLE
Snap is not updated

### ISSUE THREAD

**Issue by popey** [yvt/openspades#709] opened 2018-01-08 10:26 UTC
I noticed the snap in the store is currently 0.1.1c and not the latest 0.1.2. Can that be updated please? (I can help if needed).

https://snapcraft.io/openspades/

**Comment by yvt** [comment] 2018-01-08 10:34
Thanks for reminding us. We’re aware of that issue and it is to be handled as a part of the issue #703.
(Closing this as duplicate of #703)

**Closed by yvt** 2018-01-08 10:34 UTC
