### ISSUE TITLE
My wish list for the next version of openspades

### ISSUE THREAD

**Issue by X-DE1** [yvt/openspades#1032] opened 2022-07-26 02:21 UTC
Scale for Players, Intel and CP models
Textures for the Blocks
![shot0001](https://user-images.githubusercontent.com/101435795/180907501-1c01b7a4-664d-4e2a-8b65-6e900d48777f.jpg)
Change the palette of the block with .DAT, .PAL or image file
![shot0003](https://user-images.githubusercontent.com/101435795/180907527-b444e66a-5863-455d-9edf-2cb582535b57.jpg)
Fix Bug Shoot While Reloading
Fix Bug Pass Through Blocks

**Comment by nonperforming** [comment] 2022-07-26 21:14
#1008 
#380 
#1026 
What is "Bug Pass Through Blocks"?

**Comment by X-DE1** [comment] 2022-07-27 05:38
What is "Bug Pass Through Blocks"?
https://www.youtube.com/watch?v=9DwIEnQA1Gc

**Comment by yvt** [comment] 2022-08-02 03:25
Closing as duplicate of #1008, #380, #1026, and #857.

**Closed by yvt** 2022-08-02 03:25 UTC

**Comment by PauliusV0** [comment] 2023-04-10 06:26
Do you want your computer to explode?
