### ISSUE TITLE
OpenGL-Capable graphics accelerator is unavailable

### ISSUE THREAD

**Issue by MalexTP** [yvt/openspades#691] opened 2017-12-22 15:16 UTC
Log, line 110: https://pastebin.com/kkage2cg

![image](https://user-images.githubusercontent.com/24663715/34302899-04c7f9fe-e701-11e7-83cf-8dd808d2299b.png)

![image](https://user-images.githubusercontent.com/24663715/34302930-28c17574-e701-11e7-943e-64fd15d2ee01.png)

Manjaro Linux

**Comment by feikname** [comment] 2017-12-22 20:47
@MalexTP What'a the complete input of `glxinfo`, `mhwd -li -d` and `mhwd -l -d`? Also, do you have any additional graphics card or are you using the integrated one?

This might be a bug in our end of course, but I suspect it's a driver isue

**Comment by MalexTP** [comment] 2017-12-23 05:58
glxinfo: https://pastebin.com/htnjmrTr
mhwd -li -d: https://pastebin.com/yvf72pfG
mhwd -l -d: https://pastebin.com/8b5sEmKE
@feikname

**Comment by yvt** [comment] 2017-12-23 06:08
> ```
> 2017/12/22 10:09:40 [StartupScreenHelper.cpp:199] Failed to create SDL window: Couldn't find matching GLX visual
> 2017/12/22 10:09:40 [StartupScreenHelper.cpp:228] SDL_SetVideoMode failed: Invalid window
> ```

Duplicate of #674. Does Snapcraft work on Arch Linux too?

**Closed by yvt** 2017-12-23 06:08 UTC
Labels: troubleshooting, video driver compatibility

**Comment by feikname** [comment] 2017-12-23 06:31
Oh I didn't see the log file at the top, oops!

@MalexTP the snap version OpenGL renderer is broken in some distros currently, please try the [AUR package](https://aur.archlinux.org/packages/openspades/) maintained by @swalladge instead for now.

If you're feeling adventurous, please discover the issue and submit a PR.
