### ISSUE TITLE
OpenSpades 0.1.1 Erro Renderizador OpenGl

### ISSUE THREAD

**Issue by JadedGAMER56** [yvt/openspades#587] opened 2017-02-26 22:18 UTC
[openspades_0.1.1_erro_renderizador_opengl.txt] https://github.com/yvt/openspades/files/802329/openspades_0.1.1_erro_renderizador_opengl.txt

**Comment by feikname** [comment] 2017-02-26 23:00
Duplicate of #586

**Closed by feikname** 2017-02-26 23:00 UTC
Labels: duplicate
