### ISSUE TITLE
Weird pattern under the text

### ISSUE THREAD

**Issue by fantoro** [yvt/openspades#723] opened 2018-02-04 16:31 UTC
So I downloaded the newest version of OpenSpades on my friend's PC and I noticed this, I'm on Ultra settings and the GPU is GeForce GTX 940MX and the CPU is i5-7200U (I'm adding this if the specs matter for some reason).
![image](https://user-images.githubusercontent.com/20504699/35779633-cca7b40e-09d0-11e8-9398-525b7927e956.png)

**Comment by NotAFile** [comment] 2018-02-04 16:36
duplicate of #605

**Closed** 2018-02-06 05:15 UTC
Labels: duplicate
