### ISSUE TITLE
Mouse buttons become unresponsive in fullscreen when the cursor touches KWin screen edges

### ISSUE THREAD

**Issue by teodor6140** [yvt/openspades#638] opened 2017-08-28 06:12 UTC
While playing the mouse buttons become unresponsive for 1-5 seconds at random times
Moving the mouse still works.
I've never had this happen before on linux or windows
it doesnt affect the game setup screen; the key mapper works every time i click with the mouse

the game was compiled from the master branch

**Comment by teodor6140** [comment] 2017-08-28 17:43
I think it got fixed by itself
Maybe it's just a KWin bug

**Comment by feikname** [comment] 2017-08-28 20:27
@teodor6140, thanks for the report!

Could you provide the following information please?
 * Do you have a (not onboard) graphics card installed? If so, what driver are you using?
 * Do you have compositing enabled on KWin?

**Comment by teodor6140** [comment] 2017-08-28 22:59
@feikname
I'm on a laptop with hybrid graphics and i run the game on my amd card with the DRI_PRIME=1 variable

I think i'm using the Mesa drivers, this is my log:
```
--- OpenGL Renderer Info ---
Vendor: X.Org
Name: Gallium 0.4 on AMD HAINAN (DRM 2.49.0 / 4.10.0-32-generic, LLVM 4.0.0)
Version: 3.0 Mesa 17.0.7
Shading Language Version: 1.30
Max Texture Size: 16384
Max 3D Texture Size: 2048
Max Combined Texture Image Units: 192
Max Vertex Texture Image Units: 32
Max Varying Components: 128
```
When i start the game compositing gets automatically disabled

I usually play on low settings and when i tried on max settings it didn't get any worse
it was the same

**Comment by teodor6140** [comment] 2017-08-29 19:02
solved
It's caused by KDE's hot corners and auto-hide panel
it happens when i move my mouse at the direction of the hot corner or the auto-hide panel
i will try to write a KWin script to disable hot corners and auto-hide while playing

**Comment by teodor6140** [comment] 2017-08-29 20:25
ok i found a workaround
set an application-specific override in kde that makes the game window always on top

**Comment by feikname** [comment] 2017-08-29 22:19
@teodor6140 Glad to hear you were able to solve it (or at least have an workaround).

Could you please tell us your KDE version? I will add this to the [Common Issues](https://github.com/yvt/openspades/wiki/Common-Issues) page for reference to future people who also experience this problem.

Also, for the sake of information, this happens only on full-screen then?

**Comment by teodor6140** [comment] 2017-08-29 23:22
Yes it only happens in fullscreen
KDE neon 5.10
KDE plasma 5.10.5
KDE frameworks 5.37

**Comment by feikname** [comment] 2017-08-30 00:15
@teodor6140 If you find or develop a KWin script (or a plasmoid) for this, please share with us!

Also, related reddit thread where a KDE dev explains why this behavior happens in fullscreen and is by design: https://www.reddit.com/r/kde/comments/4l9ni0/kde5_how_do_i_disable_hot_corners_when_an/

I was going to close this issue, but this may be a OpenSpades bug.

The mouse position should be always locked during gameplay and not be able to hit screen corners, isn't that so? @yvt

**Comment by teodor6140** [comment] 2017-08-30 05:01
Locking the cursor to the center will also solve #640

**Comment by teodor6140** [comment] 2017-08-30 18:48
now i run the game from this script to disable auto hide on the panel
it doesn't disable the hot corners
```
#!/bin/bash

#set panel to always visible and restart
killall plasmashell
sed -i 's,^\(panelVisibility=\).*,\1'0',' ~/.config/plasmashellrc
nohup plasmashell >/dev/null 2>/dev/null &

DRI_PRIME=1 ./openspades #ignore the DRI_PRIME=1 thing

#after the game was closed set panel to autohide and restart
killall plasmashell
sed -i 's,^\(panelVisibility=\).*,\1'1',' ~/.config/plasmashellrc
nohup plasmashell >/dev/null 2>/dev/null &
```
it's unpractical because it restarts the plasma shell every time

**Comment by feikname** [comment] 2018-08-19 09:48
Closing this in favor of #764

**Closed by feikname** 2018-08-19 09:48 UTC
Labels: bug
