### ISSUE TITLE
Sometimes client crashes with 'Invalid Player ID' error after map switch.

### ISSUE THREAD

**Issue by noway421** [yvt/openspades#277] opened 2014-05-11 01:46 UTC
No uncommon actions were performed. It just crashed during map loading. 
Here is SysteMessages.log

```
2014/05/11 12:07:06 [Client.cpp:110] Initializing...
2014/05/11 12:07:06 [Fonts.cpp:35] Font 'Unsteady Oversteer' Loaded
2014/05/11 12:07:06 [Fonts.cpp:56] Font 'CMUSansCondensed' Loaded
2014/05/11 12:07:06 [Fonts.cpp:45] Font 'SquareFont (Large)' Loaded
2014/05/11 12:07:06 [ScriptManager.cpp:45] System function (1, 1) : ERR  : Identifier 'ClientUI' is not a data type

2014/05/11 12:07:06 [GLRenderer.cpp:298] New map loaded; freeing old renderers...
2014/05/11 12:07:06 [GLRenderer.cpp:337] No map loaded
2014/05/11 12:07:07 [Client.cpp:339] Started connecting to 'aos://3212703895:32890'
2014/05/11 12:07:07 [NetClient.cpp:323] ENet initialized
2014/05/11 12:07:07 [NetClient.cpp:328] ENet host created
2014/05/11 12:07:07 [NetClient.cpp:336] ENet Range Coder Enabled
2014/05/11 12:07:07 [NetClient.cpp:376] Using Ace of Spades 0.75 protocol
2014/05/11 12:07:07 [NetClient.cpp:387] Connecting to 3212703895:32890
2014/05/11 12:07:07 [Client.cpp:375] Netlog Started at 'NetLogs/20140511120707_3212703895_32890.log'
2014/05/11 12:07:07 [NetClient.cpp:250] Packet 0x12 [len=5] 12 00 00 18 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=19] 09 11 00 00 02 1a 00 00 00 00 80 ff 48 65 72 6f 49 4e 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=23] 09 00 00 00 02 03 00 00 00 00 80 ff 6d 61 74 61 50 49 4e 45 64 61 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=25] 09 14 01 02 02 00 00 00 00 0a ff 00 5b 41 41 54 5d 73 68 6f 6f 74 65 72 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=24] 09 09 00 01 03 01 00 00 00 00 80 ff 47 41 4d 45 52 4a 45 55 47 4f 53 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=18] 09 1a 01 01 00 0a 00 00 00 0a ff 00 50 6c 61 74 6f 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=17] 09 17 01 00 02 05 00 00 00 0a ff 00 5a 6f 69 63 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=20] 09 08 00 00 02 02 00 00 00 00 80 ff 4d 61 4c 65 69 52 6f 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=19] 09 06 00 00 02 13 00 00 00 00 80 ff 6d 6f 65 72 75 6e 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=26] 09 19 01 01 02 67 00 00 00 0a ff 00 45 76 69 6c 20 53 63 6f 74 73 6d 61 6e 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=20] 09 03 01 01 01 0b 00 00 00 0a ff 00 4b 2e 49 2e 4e 2e 47 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=27] 09 0e 00 00 02 14 00 00 00 00 80 ff 5b 53 2e 57 2e 41 2e 54 5d 20 56 69 6e 69 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=20] 09 1d 01 01 02 00 00 00 00 0a ff 00 65 6c 20 76 65 67 61 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=19] 09 12 00 00 01 00 00 00 00 00 80 ff 4d 61 6b 73 69 4d 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=25] 09 04 00 00 01 06 00 00 00 00 80 ff 44 41 4e 47 41 59 4d 45 52 37 37 37 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=25] 09 1c 00 01 02 00 00 00 00 00 80 ff 31 33 6c 34 63 6b 2d 5f 2d 54 6f 6f 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=18] 09 13 01 01 01 00 00 00 00 0a ff 00 2d 42 65 4c 2d 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=22] 09 0c 01 00 02 14 00 00 00 0a ff 00 6e 65 76 65 72 6c 61 6e 64 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=15] 09 18 01 00 00 30 00 00 00 0a ff 00 4c 58 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=16] 09 10 00 00 01 0f 00 00 00 00 80 ff 4b 61 77 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=18] 09 1b 00 00 02 01 00 00 00 00 80 ff 44 6f 6c 61 6e 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x09 [len=21] 09 0d 01 00 02 0b 00 00 00 0a ff 00 43 68 65 6e 20 48 75 61 00
2014/05/11 12:07:13 [NetClient.cpp:250] Packet 0x0f [len=84] 0f 0a f3 d9 a5 00 80 ff 0a ff 00 32 63 68 00 00 00 00 00 00 00 30 63 68 61 6e 00 00 00 00 00 00 01 04 05 00 00 00 48 42 00 00 97 43 00 00 2c 42 00 00 6c 42 00 00 59 43 00 00 70 42 00 80 ce 43
2014/05/11 12:07:13 [NetClient.cpp:1811] Map decoding succeeded.
2014/05/11 12:07:13 [GameMapWrapper.cpp:106] 39.823 msecs to rebuild
2014/05/11 12:07:13 [NetClient.cpp:1817] World initialized.
2014/05/11 12:07:13 [Client.cpp:170] World set
2014/05/11 12:07:13 [GLRenderer.cpp:298] New map loaded; freeing old renderers...
2014/05/11 12:07:13 [GLRenderer.cpp:313] Creating new renderers...
2014/05/11 12:07:13 [GLRenderer.cpp:315] Creating Terrain Shadow Map Renderer
2014/05/11 12:07:13 [GLRenderer.cpp:317] Creating TerrainRenderer
2014/05/11 12:07:13 [GLRenderer.cpp:319] Creating Minimap Renderer
2014/05/11 12:07:13 [GLRenderer.cpp:321] Creating Water Renderer
2014/05/11 12:07:13 [GLRenderer.cpp:330] Radiosity is disabled
2014/05/11 12:07:13 [GLRenderer.cpp:335] Created
2014/05/11 12:07:13 [NetClient.cpp:1826] World loaded. Processing saved packets (21)...
2014/05/11 12:07:13 [NetClient.cpp:1841] Done.
2014/05/11 12:07:16 [NetClient.cpp:1787] Sending hand shake back.
2014/05/11 12:07:16 [NetClient.cpp:1799] Sending version back.
2014/05/11 12:07:16 [GLFramebufferManager.cpp:697] New GLColorBuffer requested (w = 1280, h = 960, ifmt = 0x0063)
2014/05/11 12:07:16 [GLFramebufferManager.cpp:713] Texture allocated.
2014/05/11 12:07:16 [GLFramebufferManager.cpp:734] Framebuffer created.
2014/05/11 12:07:16 [GLFramebufferManager.cpp:697] New GLColorBuffer requested (w = 64, h = 64, ifmt = 0x0063)
2014/05/11 12:07:16 [GLFramebufferManager.cpp:713] Texture allocated.
2014/05/11 12:07:16 [GLFramebufferManager.cpp:734] Framebuffer created.
2014/05/11 12:07:16 [GLFramebufferManager.cpp:697] New GLColorBuffer requested (w = 64, h = 64, ifmt = 0x0063)
2014/05/11 12:07:16 [GLFramebufferManager.cpp:713] Texture allocated.
2014/05/11 12:07:16 [GLFramebufferManager.cpp:734] Framebuffer created.
2014/05/11 12:07:16 [GLFramebufferManager.cpp:697] New GLColorBuffer requested (w = 64, h = 64, ifmt = 0x0063)
2014/05/11 12:07:16 [GLFramebufferManager.cpp:713] Texture allocated.
2014/05/11 12:07:16 [GLFramebufferManager.cpp:734] Framebuffer created.
2014/05/11 12:07:20 [GLProgramManager.cpp:88] Loading GLSL program 'Shaders/Basic.program'
2014/05/11 12:07:20 [GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Basic.fs'
2014/05/11 12:07:20 [GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Basic.fs' in 0.568ms
2014/05/11 12:07:20 [GLProgramManager.cpp:137] Loading GLSL shader 'Shaders/Basic.vs'
2014/05/11 12:07:20 [GLProgramManager.cpp:173] Successfully compiled GLSL program 'Shaders/Basic.vs' in 0.556ms
2014/05/11 12:07:20 [GLProgramManager.cpp:129] Successfully linked GLSL program 'Shaders/Basic.program' in 6.166ms
2014/05/11 12:11:03 [GLRenderer.cpp:298] New map loaded; freeing old renderers...
2014/05/11 12:11:03 [GLRenderer.cpp:337] No map loaded
2014/05/11 12:11:03 [Client.cpp:190] World removed
2014/05/11 12:11:04 [NetClient.cpp:250] Packet 0x0f [len=84] 0f 0a 57 bf fc 00 80 ff 0a ff 00 32 63 68 00 00 00 00 00 00 00 30 63 68 61 6e 00 00 00 00 00 00 00 00 05 00 00 80 93 43 00 80 d9 43 00 00 f0 41 00 00 5c 43 00 80 d9 43 00 00 f0 41 00 00 52 43
2014/05/11 12:11:04 [NetClient.cpp:1811] Map decoding succeeded.
2014/05/11 12:11:04 [GameMapWrapper.cpp:106] 45.902 msecs to rebuild
2014/05/11 12:11:04 [NetClient.cpp:1817] World initialized.
2014/05/11 12:11:04 [Client.cpp:170] World set
2014/05/11 12:11:04 [GLRenderer.cpp:298] New map loaded; freeing old renderers...
2014/05/11 12:11:04 [GLRenderer.cpp:313] Creating new renderers...
2014/05/11 12:11:04 [GLRenderer.cpp:315] Creating Terrain Shadow Map Renderer
2014/05/11 12:11:04 [GLRenderer.cpp:317] Creating TerrainRenderer
2014/05/11 12:11:04 [GLRenderer.cpp:319] Creating Minimap Renderer
2014/05/11 12:11:04 [GLRenderer.cpp:321] Creating Water Renderer
2014/05/11 12:11:05 [GLRenderer.cpp:330] Radiosity is disabled
2014/05/11 12:11:05 [GLRenderer.cpp:335] Created
2014/05/11 12:11:05 [NetClient.cpp:1826] World loaded. Processing saved packets (0)...
2014/05/11 12:11:05 [NetClient.cpp:1841] Done.
2014/05/11 12:32:13 [GLRenderer.cpp:298] New map loaded; freeing old renderers...
2014/05/11 12:32:13 [GLRenderer.cpp:337] No map loaded
2014/05/11 12:32:13 [Client.cpp:190] World removed
2014/05/11 12:32:15 [NetClient.cpp:250] Packet 0x1c [len=4] 1c 0a 0a 28
2014/05/11 12:32:15 [NetClient.cpp:557] Map decoder returned error. Maybe we will get more data...:
EOF reached while reading compressed data
at /home/noway/compiling/openspades/Sources/Core/DeflateStream.cpp:237
void spades::DeflateStream::FillBuffer() at DeflateStream.cpp:183
virtual size_t spades::DeflateStream::Read(void*, size_t) at DeflateStream.cpp:264
virtual std::string spades::IStream::Read(size_t) at IStream.cpp:51
virtual std::string spades::IStream::ReadAllBytes() at IStream.cpp:64
static spades::client::GameMap* spades::client::GameMap::Load(spades::IStream*) at GameMap.cpp:508
void spades::client::NetClient::MapLoaded() at NetClient.cpp:1804
void spades::client::NetClient::DoEvents(int) at NetClient.cpp:452
virtual void spades::client::Client::RunFrame(float) at Client.cpp:382
virtual void spades::gui::MainScreen::RunFrame(float) at MainScreen.cpp:234
void spades::gui::SDLRunner::Run(int, int) at SDLRunner.cpp:414
void spades::gui::Runner::Run() at Runner.cpp:75
void spades::gui::Runner::RunProtected() at Runner.cpp:48
int main(int, char**) at Main.cpp:334

2014/05/11 12:32:17 [NetClient.cpp:250] Packet 0x0f [len=84] 0f 0a 0b 0c 0c 00 80 ff 0a ff 00 32 63 68 00 00 00 00 00 00 00 30 63 68 61 6e 00 00 00 00 00 00 00 00 05 00 00 00 e5 43 00 00 81 43 00 00 6c 42 00 00 e5 43 00 80 af 43 00 00 68 42 00 00 b6 42
2014/05/11 12:32:17 [NetClient.cpp:250] Packet 0x0b [len=15] 0b 00 00 00 00 e5 43 00 00 81 43 00 00 74 42
2014/05/11 12:32:17 [NetClient.cpp:250] Packet 0x0b [len=15] 0b 02 00 00 00 b6 42 00 00 81 43 00 00 70 42
2014/05/11 12:32:17 [NetClient.cpp:250] Packet 0x0b [len=15] 0b 01 01 00 00 e5 43 00 80 af 43 00 00 74 42
2014/05/11 12:32:17 [NetClient.cpp:250] Packet 0x0b [len=15] 0b 03 01 00 00 b6 42 00 80 a4 43 00 00 70 42
2014/05/11 12:32:17 [NetClient.cpp:250] Packet 0x1b [len=5] 1b 00 ef df bf
2014/05/11 12:32:17 [NetClient.cpp:250] Packet 0x11 [len=56] 11 23 02 53 75 70 20 74 68 65 72 65 2e 20 4b 61 72 74 61 3a 20 53 77 61 6d 70 20 4c 61 6e 64 73 20 6b 6f 74 6f 72 79 75 20 73 64 64 65 6c 61 6c 69 3a 20 76 5e 33 2e 00
2014/05/11 12:32:17 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:18 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x11 [len=54] 11 23 02 52 65 7a 79 6d 3a 20 50 75 73 68 2e 20 44 4f 53 54 41 56 27 54 45 20 49 4e 54 45 4c 20 4e 41 20 42 41 5a 55 20 4c 59 55 42 4f 59 20 43 45 4e 4f 59 2e 00
2014/05/11 12:32:19 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:20 [NetClient.cpp:250] Packet 0x02 [len=769] 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2014/05/11 12:32:21 [NetClient.cpp:1811] Map decoding succeeded.
2014/05/11 12:32:21 [GameMapWrapper.cpp:106] 23.756 msecs to rebuild
2014/05/11 12:32:21 [NetClient.cpp:1817] World initialized.
2014/05/11 12:32:21 [Client.cpp:170] World set
2014/05/11 12:32:21 [GLRenderer.cpp:298] New map loaded; freeing old renderers...
2014/05/11 12:32:21 [GLRenderer.cpp:313] Creating new renderers...
2014/05/11 12:32:21 [GLRenderer.cpp:315] Creating Terrain Shadow Map Renderer
2014/05/11 12:32:21 [GLRenderer.cpp:317] Creating TerrainRenderer
2014/05/11 12:32:21 [GLRenderer.cpp:319] Creating Minimap Renderer
2014/05/11 12:32:21 [GLRenderer.cpp:321] Creating Water Renderer
2014/05/11 12:32:21 [GLRenderer.cpp:330] Radiosity is disabled
2014/05/11 12:32:21 [GLRenderer.cpp:335] Created
2014/05/11 12:32:21 [NetClient.cpp:1826] World loaded. Processing saved packets (39)...
2014/05/11 12:32:21 [NetClient.cpp:416] Waiting for graceful disconnection
2014/05/11 12:32:21 [Client.cpp:410] Disconnected because of error:
Invalid Player ID 10: Doesn't exist
at /home/noway/compiling/openspades/Sources/Client/NetClient.cpp:649
spades::client::Player* spades::client::NetClient::GetPlayer(int) at NetClient.cpp:643
void spades::client::NetClient::Handle(spades::client::NetPacketReader&) at NetClient.cpp:708
void spades::client::NetClient::MapLoaded() at NetClient.cpp:1804
void spades::client::NetClient::DoEvents(int) at NetClient.cpp:452
virtual void spades::client::Client::RunFrame(float) at Client.cpp:382
virtual void spades::gui::MainScreen::RunFrame(float) at MainScreen.cpp:234
void spades::gui::SDLRunner::Run(int, int) at SDLRunner.cpp:414
void spades::gui::Runner::Run() at Runner.cpp:75
void spades::gui::Runner::RunProtected() at Runner.cpp:48
int main(int, char**) at Main.cpp:334

2014/05/11 12:32:21 [MainScreen.cpp:246] [!] Error while running a game client: Invalid Player ID 10: Doesn't exist
at /home/noway/compiling/openspades/Sources/Client/NetClient.cpp:649
spades::client::Player* spades::client::NetClient::GetPlayer(int) at NetClient.cpp:643
void spades::client::NetClient::Handle(spades::client::NetPacketReader&) at NetClient.cpp:708
void spades::client::NetClient::MapLoaded() at NetClient.cpp:1804
void spades::client::NetClient::DoEvents(int) at NetClient.cpp:452
virtual void spades::client::Client::RunFrame(float) at Client.cpp:382
virtual void spades::gui::MainScreen::RunFrame(float) at MainScreen.cpp:234
void spades::gui::SDLRunner::Run(int, int) at SDLRunner.cpp:414
void spades::gui::Runner::Run() at Runner.cpp:75
void spades::gui::Runner::RunProtected() at Runner.cpp:48
int main(int, char**) at Main.cpp:334

2014/05/11 12:32:21 [Client.cpp:207] Closing netlog
2014/05/11 12:32:21 [Client.cpp:212] Disconnecting
2014/05/11 12:32:21 [NetClient.cpp:361] ENet host destroyed
2014/05/11 12:32:21 [Client.cpp:217] Disconnected
2014/05/11 12:32:21 [GLRenderer.cpp:298] New map loaded; freeing old renderers...
2014/05/11 12:32:21 [GLRenderer.cpp:337] No map loaded
2014/05/11 12:32:21 [GLRenderer.cpp:298] New map loaded; freeing old renderers...
2014/05/11 12:32:21 [GLRenderer.cpp:313] Creating new renderers...
2014/05/11 12:32:21 [GLRenderer.cpp:315] Creating Terrain Shadow Map Renderer
2014/05/11 12:32:21 [GLRenderer.cpp:317] Creating TerrainRenderer
2014/05/11 12:32:21 [GLRenderer.cpp:319] Creating Minimap Renderer
2014/05/11 12:32:21 [GLRenderer.cpp:321] Creating Water Renderer
2014/05/11 12:32:21 [GLRenderer.cpp:330] Radiosity is disabled
2014/05/11 12:32:21 [GLRenderer.cpp:335] Created
```

This happens not often, though sometime it does.

**Comment by NotAFile** [comment] 2015-09-13 23:28
same as #62

**Comment by noway421** [comment] 2015-09-20 11:08
I believe it's not. The log in issue #62 does not have "Invalid Player" error.

**Comment by NotAFile** [comment] 2015-09-20 15:30
sorry, that was not the issue I meant to link. Thanks!

**Comment by yvt** [comment] 2016-11-22 16:51
Duplicate of the issue #66.

**Closed by yvt** 2016-11-22 16:51 UTC
Labels: AoSβ compatibility, bug
