### ISSUE TITLE
Support for older Skins 

### ISSUE THREAD

**Issue by RocketNinja15** [yvt/openspades#951] opened 2021-05-01 00:48 UTC
Hi, 
I have recently spent way too long trying to get skins to work. I was chatting with the build and shoot discord until I realized that openspades now uses .opus. That means that all of the skins don’t work because the scripts reference .wav

**Comment by yvt** [comment] 2021-05-01 08:05
Duplicate of #689 

Temporary work-around from <https://github.com/yvt/openspades/issues/632#issuecomment-326754335> (link added):

>  renaming `pak000-Nonfree.pak` to `pak001-Nonfree.pak`, copying the `pak010-BaseSkin.pak` from [0.0.12](https://github.com/yvt/openspades/releases/tag/v0.0.12), and then renaming it to `pak000-BaseSkin.pak` should do the trick. (Untested)

**Closed by yvt** 2021-05-01 08:05 UTC
