### ISSUE TITLE
"File truncated" error on map with top layer blocks

### ISSUE THREAD

**Issue by 1AmYF** [yvt/openspades#812] opened 2019-03-13 16:44 UTC
Joining a server with a map with lots of blocks on the upper layers (only hold by a few pillars) results in "File truncated" error. Joining with the classic 0.75 client works.
```
[C:\Users\tcpp\Documents\Projects\openspades\Sources\Gui\Runner.cpp:48] [!] Unhandled exception in SDLRunner:
File truncated
at C:\Users\tcpp\Documents\Projects\openspades\Sources\Client\GameMap.cpp:552
```
Example map to reproduce the error:
https://www.dropbox.com/s/ne1np6ntn6449tu/file_truncated_map.zip?dl=1

**Comment by feikname** [comment] 2019-03-13 20:18
Related: #362

**Comment by NotAFile** [comment] 2019-05-26 19:10
I think both of these should be fixed by the state packet fix?

**Comment by yvt** [comment] 2019-05-29 09:23
This was caused by incorrect array bounds checks in the map loader, which were fixed in #830 when the map loader was partially rewritten.

**Closed by yvt** 2019-05-29 09:23 UTC
Labels: bug
