### ISSUE TITLE
Compilation fails on Raspberry pi OS (armv7l,armhf)

### ISSUE THREAD

**Issue by CPXMC** [yvt/openspades#931] opened 2021-01-01 10:14 UTC
I use 3B+ model to compile

This is part of the output
```
/usr/bin/ld: ../lib/libAngelscript.a(as_callfunc.cpp.o): in function `CallSystemFunction(int, asCContext*)':
as_callfunc.cpp:(.text+0x2d4): undefined reference to `CallSystemFunctionNative(asCContext*, asCScriptFunction*, void*, unsigned long*, void*, unsigned long long&, void*)'
collect2: error: ld returned 1 exit status
make[2]: *** [Sources/CMakeFiles/OpenSpades.dir/build.make:3561：bin/openspades] 错误 1
make[1]: *** [CMakeFiles/Makefile2:230：Sources/CMakeFiles/OpenSpades.dir/all] 错误 2
make: *** [Makefile:152：all] 错误 2
```

**Comment by yvt** [comment] 2021-01-28 05:16
Duplicate of #416

**Closed by yvt** 2021-01-28 05:16 UTC
Labels: compilation-issue, duplicate
