### ISSUE TITLE
Software renderer has greater frame rate than OpenGL

### ISSUE THREAD

**Issue by Xenoxis** [yvt/openspades#508] opened 2016-12-27 14:03 UTC
Hello, i have download the latest build of OpenSpades (issue : #398), but i have better performance with the Software rendering rather the OpenGL rendering ,and i don't know why ...

I have set all the graphical options to the minimum (also the resolution, because I'm in full screen ...)

Do you have an idea ? Thanks in advance ...

**Comment by feikname** [comment] 2016-12-28 00:15
Could you specify your graphics card(which Intel Graphics) and your windows version please?

**Comment by feikname** [comment] 2016-12-28 00:37
Also, does this happens with other games? 

If your graphics card in the one built-in with the processor, I have bad news. Those graphic cards usually are fine for most applications, but tend to not do so well with more recent games. If that's the case, maybe this is happening because your CPU can handle the rendering better than its built-in graphics card.

I can see from #398 that you have `Max Varying Components: 41`. I don't know how good or bad this means, but compared to mine it's over 3 times less, perhaps thats the cause.

Of couse, it can also be a bug, we need to do troubleshooting first.

**Comment by Xenoxis** [comment] 2016-12-28 09:29
I have the latest Driver of the Intel HD Graphics (Arrandale architecture) on a Windows 7 x64

In other games who use OpenGL (like Minecraft), i have a really special thing : when i try to display a lot of entity or blocks (with a view-distance of 8), my GPU down clock it-self because my CPU is at 100% of utilization, it's probably for the heat limit or the TDP limit ... i have very bad fps (10-15) but when i fix it (downgrade the view-distance or see my foots), i have between 30-50 fps, and my GPU is at full speed at this time ... i don't know if this thing happen in OpenSpade with OpenGL rendering ...

 The results with the "Show-Statistics" option : 
- With OpenGl rendering : ~5 fps (i'm also lag in the server list menu : the mouse lag xD)
- With the software rendering :  ~ 23 fps

**Comment by Tapmemer** [comment] 2016-12-31 11:12
must be volumetric fog or some that you enabled. it happens to slow almost anybody down even in menu

**Comment by feikname** [comment] 2018-08-19 10:00
@Xenoxis Do you still have interest in trying to solve this issue? If no reply is given in 1 week, I will close this.

**Closed** 2018-10-15 20:45 UTC
Labels: performance, renderer, troubleshooting
