### ISSUE TITLE
raspberry pi 3

### ISSUE THREAD

**Issue by humanopi** [yvt/openspades#940] opened 2021-01-27 23:42 UTC
something is wrong but i dont know what

pi@raspberrypi:~/openspades/openspades.mk $ sudo make install
[  1%] Building paks
/home/pi/openspades/Resources /home/pi/openspades/openspades.mk/Resources
/home/pi/openspades/Resources/mkpak.sh: linha 22: zip: comando não encontrado
/home/pi/openspades/Resources/mkpak.sh: linha 27: zip: comando não encontrado
/home/pi/openspades/Resources/mkpak.sh: linha 29: zip: comando não encontrado
/home/pi/openspades/Resources/mkpak.sh: linha 33: zip: comando não encontrado
/home/pi/openspades/Resources/mkpak.sh: linha 35: zip: comando não encontrado
/home/pi/openspades/openspades.mk/Resources
[  1%] Building assets
[  1%] Built target OpenSpades_Resources
[  1%] Built target OpenSpades_Unix
[  1%] Downloading non-GPL assets
[  2%] Built target OpenSpades_Resources_DevPaks
[  6%] Built target Angelscript_addons
[ 17%] Built target Angelscript
[ 18%] Linking CXX executable ../bin/openspades
/usr/bin/ld: ../lib/libAngelscript.a(as_callfunc.cpp.o): na função "CallSystemFunction(int, asCContext*)":
/home/pi/openspades/Sources/AngelScript/source/as_callfunc.cpp:703: referência não definida para "CallSystemFunctionNative(asCContext*, asCScriptFunction*, void*, unsigned long*, void*, unsigned long long&, void*)"
collect2: error: ld returned 1 exit status
make[2]: *** [Sources/CMakeFiles/OpenSpades.dir/build.make:3576: bin/openspades] Error 1
make[1]: *** [CMakeFiles/Makefile2:230: Sources/CMakeFiles/OpenSpades.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by yvt** [comment] 2021-01-28 05:18
Duplicate of #416

**Closed by yvt** 2021-01-28 05:18 UTC
