### ISSUE TITLE
Setting aren't being saved!

### ISSUE THREAD

**Issue by konrad6dpl** [yvt/openspades#341] opened 2015-01-27 23:01 UTC
I have to constantly change the settings because they not save. Name and all general settings.
![problem1](https://cloud.githubusercontent.com/assets/10732520/5929079/ce1fb5c2-a680-11e4-91f5-80175660ceb8.png)

**Comment by feikname** [comment] 2015-04-30 22:26
**Note:** This error can be reproduced in the following ways:

**Method 1:**
  1- Open a instance of OpenSpades
  2- Open a second instance of it
  3- Now the settings file is being utilized by the first instance and can't be readed nor written.

**Method 2: **
  1- Go to the OpenSpades settings folder *(%APPDATA%/OpenSpades on Windows)*
  2- Change the folder permissions to read-only or have some proccess busy with it.

**Comment by feikname** [comment] 2016-11-23 21:27
Seems to be a problem with your environment, so I am closing this.

Please reopen the issue or create a new if you still wish to try to solve it.

**Closed by feikname** 2016-11-23 21:27 UTC
Labels: bug, needs-more-info, wontfix
