### ISSUE TITLE
Add demo recording and playback.

### ISSUE THREAD

**Issue by roboman2444** [yvt/openspades#517] opened 2017-01-01 16:01 UTC
So we can have "replays" of games.
See quake, quake3, darkplaces, UT, etc for an example.

**Comment by feikname** [comment] 2017-01-01 16:10
Duplicate of #57

**Closed by feikname** 2017-01-01 16:10 UTC
Labels: duplicate

**Comment by Tapmemer** [comment] 2017-01-02 21:33
he means the movements etc. gets recorded just like soure engine does with demos
