### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by dany-on-demand** [yvt/openspades#71] opened 2013-09-19 19:04 UTC
I didn't find any style guide in the project, would be a good idea to have one at some point.

**Comment by VelocityRa** [comment] 2016-11-20 14:20
We have Travis now so I'm closing this.

**Comment by theunknownxy** [comment] 2016-11-20 19:41
@VelocityRa Actually the problem is still there and Travis only ensures that openspades builds on Linux, which is unrelated to this issue.
Currently the code base is a mixture of space/tabs indentation. I propose to use clang-format or [editorconfig](http://editorconfig.org/)(for some basic settings like tabs/spaces) or both(clang-format for C++ and editorconfig for angelscript).

**Comment by feikname** [comment] 2016-11-20 19:57
Oh yes, the code base is hella inconsistent.

**Comment by feikname** [comment] 2016-11-20 20:02
@VelocityRa I think this is a issue where the `discussion` tag would be appropriate.

**Comment by VelocityRa** [comment] 2016-11-20 20:12
Right, sorry for closing this then.

**Comment by feikname** [comment] 2016-11-20 20:15
@yvt thoughts on this?

**Comment by yvt** [comment] 2016-11-21 11:06
Haven't tried clang-format and editorconfig yet, but they look good to me.

**Comment by VelocityRa** [comment] 2016-11-21 13:21
The [LLVM coding standards](http://llvm.org/docs/CodingStandards.html) look good to me.
For the other options available check [this](http://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options).
Maybe it would be better to use LLVM, but with `IndentWidth` set to 4 spaces?
[Webkit](https://webkit.org/code-style-guidelines/) looks fine as well.

**Comment by theunknownxy** [comment] 2016-12-01 21:01
I suggest using clang-format only on modified or new code, because otherwise it would break git blame and similar tools. clang-format includes a [nice script](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) which only formats changed lines.

**Comment by VelocityRa** [comment] 2016-12-01 21:29
1) Most of the code has already been written. A lot of commits from now on will modify that code.

2) Most of the code is YVT's anyways. Would it really matter that much? Besides, you can see the history of each file anyway, git blame is just a small convenience.

Given those points, I disagree, and I think that it would make sense for @yvt to make the formatting commit.

**Comment by theunknownxy** [comment] 2016-12-01 21:39
git blame is not (only 😉) about blaming a person, it's more about seeing why something was changed. But of course it's yvt's decision.

**Comment by feikname** [comment] 2016-12-03 21:47
Closing this, as #471 fixes it. (400 issues/pull requests later! lol)

**Closed by feikname** 2016-12-03 21:47 UTC
Labels: discussion, refactoring
