### ISSUE TITLE
Netclient.cpp

### ISSUE THREAD

**Issue by roadapathy** [yvt/openspades#588] opened 2017-02-27 19:47 UTC
Well, I still have this....

![screenshot_2017-02-26_15-33-54](https://cloud.githubusercontent.com/assets/6241235/23376838/9e96bf70-fcfb-11e6-80e8-36c6c1b716de.png)

and some Windows people reported a crash when the server changes maps too.

**Comment by NotAFile** [comment] 2017-02-27 19:55
Duplicate of #66

**Closed** 2017-02-27 21:53 UTC
Labels: bug, duplicate
