### ISSUE TITLE
Indvalid player ID error on map change.

### ISSUE THREAD

**Issue by DarKKsd** [yvt/openspades#458] opened 2016-11-22 16:46 UTC
Hi, when map changes, after a new one begins loading, i quite often get and error about invalid player ID. 
![image](https://cloud.githubusercontent.com/assets/11412175/20532820/fe56b794-b0e3-11e6-8946-36c988e55568.png)

**Comment by yvt** [comment] 2016-11-22 17:05
Duplicate of #66.

**Closed by yvt** 2016-11-22 17:05 UTC
Labels: bug, duplicate
