### ISSUE TITLE
Reverse chat direction

### ISSUE THREAD

**Issue by NotAFile** [yvt/openspades#637] opened 2017-08-02 19:05 UTC
As far as I know AoS/OS is the only game in which text flows bottom up. It is highly unintuitive and hard to read.

I tried messing with the MessageView to change this, but I gave up after it became apparent this was not a quick fix.

**Comment by feikname** [comment] 2017-08-28 21:52
Duplicate of #72.

**Closed by feikname** 2017-08-28 21:52 UTC
Labels: duplicate, enhancement
