### ISSUE TITLE
Update the snap version to the pre-release 0.1.5 with GNU 9

### ISSUE THREAD

**Issue by darkvoilet** [yvt/openspades#1009] opened 2022-04-09 22:30 UTC
Please update the snap version of OpenSpades to the pre-release 0.1.5 like what you can get on the github.
It will be so nice to have the new version like the one github has now for Linux.
Thanks and good luck!

**Comment by yvt** [comment] 2022-04-10 06:45
Closing as duplicate of #703

**Closed by yvt** 2022-04-10 06:45 UTC
