### ISSUE TITLE
World Updates do not update player animation state

### ISSUE THREAD

**Issue by NotAFile** [yvt/openspades#957] opened 2021-05-18 14:17 UTC
Normal player movement uses `player.MovePlayer`, however world updates use `player.SetPosition`. This means that movement caused by world updates does not update the animation state. This becomes especially visible at higher server tick rates, as in these examples:

https://youtu.be/gzkpl2ZZAwo
https://youtu.be/FgjLTdxvuvs

**Comment by Haxk20** [comment] 2021-05-18 17:14
Can confirm this issue. Im experiencing this on SpadesX server which has 60ups by default.

**Comment by Haxk20** [comment] 2021-07-09 22:32
@yvt Its been a while and no info if this is being looked into or something. Can you give us some info ?

**Comment by yvt** [comment] 2021-07-10 12:41
Actually, the movements of non-local players are calculated exactly in the same way as a local player except that their positions and velocities are constantly overwritten by the values sent by a server. The velocities are calculated by taking the finite differences of the two most recently received positions:

https://github.com/yvt/openspades/blob/f2f56ff4faa50d112f2861f7f8ca1bd12cabdcad/Sources/Client/NetClient.cpp#L806-L818

... and translated into walk cycles by time-integrating `sqrt(velocity.x^2 + velocity.y^2)`.

https://github.com/yvt/openspades/blob/f2f56ff4faa50d112f2861f7f8ca1bd12cabdcad/Sources/Client/Player.cpp#L1215-L1234

https://github.com/yvt/openspades/blob/f2f56ff4faa50d112f2861f7f8ca1bd12cabdcad/Sources/Client/Player.cpp#L1337-L1339

I don't know how a high tick rate could disrupt this process (without causing a more serious issue, to be precise, because there's a bug in the first code snippet above, which will only manifest in a more game-breaking way).

**Comment by Haxk20** [comment] 2021-07-10 15:08
> Actually, the movements of non-local players are calculated exactly in the same way as a local player except that their positions *and* velocities are constantly overwritten by the values sent by a server. The velocities are calculated by taking the finite differences of the two most recently received positions:
> 
> https://github.com/yvt/openspades/blob/f2f56ff4faa50d112f2861f7f8ca1bd12cabdcad/Sources/Client/NetClient.cpp#L806-L818
> 
> ... and translated into walk cycles by time-integrating `sqrt(velocity.x^2 + velocity.y^2)`.
> 
> https://github.com/yvt/openspades/blob/f2f56ff4faa50d112f2861f7f8ca1bd12cabdcad/Sources/Client/Player.cpp#L1215-L1234
> 
> https://github.com/yvt/openspades/blob/f2f56ff4faa50d112f2861f7f8ca1bd12cabdcad/Sources/Client/Player.cpp#L1337-L1339
> 
> I don't know how a high tick rate could disrupt this process (without causing a more serious issue, to be precise, because there's a bug in the first code snippet above, which will only manifest in a more game-breaking way).

It isnt the calculations that are wrong. They are for sure correct. The issue is with animations.

**Comment by yvt** [comment] 2021-07-10 15:36
The walk cycle (a.k.a. the walking animation) is calculated based on the return value of `GetWalkAnimationProgress`:

https://github.com/yvt/openspades/blob/f2f56ff4faa50d112f2861f7f8ca1bd12cabdcad/Sources/Client/ClientPlayer.cpp#L934-L941

I thought the "animation" referred to this?

**Comment by Haxk20** [comment] 2021-07-10 23:27
Interesting. Well either way its quite useless to speculate on why it shouldnt break.

It does sadly break somehow.

**Comment by Haxk20** [comment] 2021-12-08 00:28
Maybe lets revisit this as its STILL an issue.

**Comment by Haxk20** [comment] 2021-12-14 22:34
NetClient.cpp line 813.

`timespan = std::max(0.08f, timespan);`

Change 0.08 to 0.0016 and animations will work very decently on 60ups. But this entire animation thing is very dependent on
this. So it makes the player jump around a bit.

I did not check what BetterSpades does for the animations but maybe @yvt could implement it the way @xtreme8000 did
as his implementation works on any UPS i throw at it. Even at crazy numbers like 300.

But maybe he is just limiting the animations.

The best solution is to rewrite the code for this to be less dependent on UPS and actually update and render the animations at the FPS.
Or well the hacky way is to just figure out the UPS of local client and update animations according to this.

Thanks to @Rakete175 for shooting my attention to this number :)

**Comment by yvt** [comment] 2021-12-15 13:05
Fixed by commit c0414e9906b8925ca0a262bf1c12813189d8a04c. Turns out, the vanilla client doesn't update player velocity vectors upon receiving `WorldUpdate` packets.

**Closed by yvt** 2021-12-15 13:05 UTC
